#!/usr/bin/env bash
set -euo pipefail

# ─── 常量配置（无需传参，自动执行）───────────────────────────────────────────
BUSINESS="hotel"
ENTRY_SKILL="AGENTS.md"
SKILL_REPO_URL="ssh://git@git.sankuai.com/nib/trade-hotel-ai.git"

# ─── 工作根目录解析（分层自动解析，兼容任意环境）─────────────────────────────
# 优先级：显式覆盖 DUTY_WORKSPACE_ROOT > 平台注入 CATPAW_WORKSPACE > 容器标准位
#         /workspace/projects（可写时）> HOME 兜底。容器自动用标准位，本机/其他
#         环境自动回退，无需手工配置；解析结果写入 env 文件供全链路统一复用。
# 通用助手：容器标准位 $1 可创建且可写则用之，否则回退 $2。
prefer_writable_dir() {
  if mkdir -p "$1" 2>/dev/null && [[ -w "$1" ]]; then
    echo "$1"
  else
    echo "$2"
  fi
}

resolve_workspace_root() {
  if [[ -n "${DUTY_WORKSPACE_ROOT:-}" ]]; then
    echo "$DUTY_WORKSPACE_ROOT"; return
  fi
  if [[ -n "${CATPAW_WORKSPACE:-}" && -d "$CATPAW_WORKSPACE" ]]; then
    echo "$CATPAW_WORKSPACE"; return
  fi
  prefer_writable_dir /workspace/projects "${CATPAW_DATA_DIR:-$HOME/.catpaw}/projects"
}
WORKSPACE_ROOT="$(resolve_workspace_root)"

KNOWLEDGE_REPO="$WORKSPACE_ROOT/trade-hotel-ai"
# 业务源码仓库直接克隆到工作根目录下（与知识库仓库同级），不再有 repos/ 中间层
REPOS_DIR="$WORKSPACE_ROOT"

# ─── 外部 skill 目录解析（与工作根目录同源的分层策略）──────────────────────────
# 优先级：显式覆盖 DUTY_SKILLS_DIR > 跟随工作根落点（工作根在 /workspace 下用
#         /workspace/skills 与 projects 同级，否则用 $WORKSPACE_ROOT/.skills），
#         避免 skills 与 projects 分裂到不同根。外部市场 skill（如 logcenter-query-cli）
#         统一装于此，有则直接用、无则用 mtskills --dir 拉取。
resolve_skills_dir() {
  if [[ -n "${DUTY_SKILLS_DIR:-}" ]]; then
    echo "$DUTY_SKILLS_DIR"; return
  fi
  case "$WORKSPACE_ROOT" in
    /workspace/*) prefer_writable_dir /workspace/skills "$WORKSPACE_ROOT/.skills" ;;
    *)            echo "$WORKSPACE_ROOT/.skills" ;;
  esac
}
SKILLS_DIR="$(resolve_skills_dir)"
# 需要预装的外部市场 skill 清单（缺失时通过 mtskills --dir 拉取到 $SKILLS_DIR）
# 注：logcenter-query-cli 自带可执行脚本 lc-query；watson-cli/raptor-query-cli 仅含文档，
#     真正的 watson/raptor 二进制由各自 SKILL.md 指引的 pip/uv 安装（在系统 PATH，不在 $SKILLS_DIR）。
REQUIRED_SKILLS=(logcenter-query-cli watson-cli raptor-query-cli)

# agent 运行时数据目录（存放 env 文件）
AGENT_DATA_DIR="${CATPAW_DATA_DIR:-$HOME/.catpaw/data}"
BIN_DIR="$WORKSPACE_ROOT/.bin"
ENV_FILE="$AGENT_DATA_DIR/duty-$BUSINESS.env"
ENV_FILE_TMP="$ENV_FILE.tmp"
STATE_CLI_SRC="$KNOWLEDGE_REPO/oncall/cli/state-cli/bin/state-cli"
STATE_PKG_SRC="$KNOWLEDGE_REPO/oncall/cli/state-cli/state_cli"

echo "🦞 初始化 trade-hotel-oncall: business=$BUSINESS, skill=$ENTRY_SKILL"
echo "   workspace root: $WORKSPACE_ROOT"
echo "   knowledge repo: $KNOWLEDGE_REPO"
echo "   业务源码目录:   $REPOS_DIR"
echo "   外部skill目录:  $SKILLS_DIR"
echo "   env file:       $ENV_FILE"

# ─── Step 1: 创建必要目录 ──────────────────────────────────────────────────
echo ""
echo "📁 Step 1: 创建必要目录..."
mkdir -p "$WORKSPACE_ROOT"
mkdir -p "$BIN_DIR"
mkdir -p "$SKILLS_DIR"
mkdir -p "$AGENT_DATA_DIR"
echo "   ✅ 目录创建完成"

# ─── Step 2: 克隆/更新知识与 skill 仓库 ───────────────────────────────────
echo ""
echo "📥 Step 2: 克隆/更新知识与 skill 仓库..."
if [[ -d "$KNOWLEDGE_REPO/.git" ]]; then
  echo "   🔄 仓库已存在，执行 git fetch + reset --hard 强制同步..."
  if git -C "$KNOWLEDGE_REPO" fetch origin -q 2>&1 && \
     git -C "$KNOWLEDGE_REPO" reset --hard origin/master -q 2>&1; then
    echo "   ✅ 知识与 skill 仓库已强制同步到远端最新版本"
  else
    echo "   ⚠️  git fetch/reset 失败，继续使用本地已有版本"
  fi
else
  echo "   📥 仓库不存在，开始克隆..."
  if git clone "$SKILL_REPO_URL" "$KNOWLEDGE_REPO" -q 2>&1; then
    echo "   ✅ 知识与 skill 仓库克隆成功: $KNOWLEDGE_REPO"
  else
    echo "   ❌ 仓库克隆失败（请检查 Git SSH 权限及网络连接）"
    exit 1
  fi
fi

mkdir -p "$KNOWLEDGE_REPO/config"

# ─── Step 3: 生成 duty 环境文件 ───────────────────────────────────────────
echo ""
echo "🧾 Step 3: 生成 duty 环境文件..."
cat > "$ENV_FILE_TMP" <<EOF
# Generated by trade-hotel-oncall duty-agent-init.sh
export DUTY_BUSINESS=$(printf '%q' "$BUSINESS")
export DUTY_ENTRY_SKILL=$(printf '%q' "$ENTRY_SKILL")
export DUTY_WORKSPACE_ROOT=$(printf '%q' "$WORKSPACE_ROOT")
export DUTY_KNOWLEDGE_REPO=$(printf '%q' "$KNOWLEDGE_REPO")
export DUTY_REPOS_DIR=$(printf '%q' "$REPOS_DIR")
export DUTY_SKILLS_DIR=$(printf '%q' "$SKILLS_DIR")
# DUTY_WORKSPACE 为 DUTY_KNOWLEDGE_REPO 的向后兼容别名（部分下游仍按此回退读取）
export DUTY_WORKSPACE=$(printf '%q' "$KNOWLEDGE_REPO")
export DUTY_SKILL_REPO_URL=$(printf '%q' "$SKILL_REPO_URL")
export CATPAW_DATA_DIR=$(printf '%q' "$AGENT_DATA_DIR")
export PATH="$(printf '%q' "$BIN_DIR"):\$PATH"
EOF
mv "$ENV_FILE_TMP" "$ENV_FILE"
echo "   ✅ duty 环境文件已生成: $ENV_FILE"

# ─── Step 4: 安装强依赖 CLI（mtskills + mtdev）────────────────────────────
echo ""
echo "📦 Step 4: 检查/安装强依赖 CLI..."
# mtskills：用于安装外部市场 skill
if command -v mtskills &>/dev/null; then
  echo "   ✅ mtskills 已安装"
else
  echo "   📦 mtskills 未安装，正在安装..."
  if npm i -g @mtfe/mtskills --registry=http://r.npm.sankuai.com 2>&1; then
    echo "   ✅ mtskills 安装成功"
  else
    echo "   ❌ mtskills 安装失败，logcenter-query-cli 等工具可能无法通过 mtskills 安装"
    echo "      请手动执行: npm i -g @mtfe/mtskills --registry=http://r.npm.sankuai.com"
  fi
fi
# mtdev（强依赖）：订单证据采集（`AGENTS.md` 步骤三/四/六，经 octo_order_query.py）必需。
# 每次执行都主动安装/更新（uv tool install --upgrade 幂等）；安装命令口径见 atomic-tools.md。
if command -v uv &>/dev/null; then
  echo "   📦 安装/更新 mtdev（强依赖）..."
  if UV_INDEX_URL=https://pypi.sankuai.com/simple/ uv tool install --upgrade mt-dev-cli 2>&1; then
    echo "   ✅ mtdev 已安装/更新"
  else
    echo "   ❌ mtdev 安装失败（强依赖；AGENTS.md 步骤零会再次校验并阻塞流程）"
    echo "      请手动执行: UV_INDEX_URL=https://pypi.sankuai.com/simple/ uv tool install --upgrade mt-dev-cli"
  fi
else
  echo "   ⚠️  未找到 uv，无法安装强依赖 mtdev；请先安装 uv 或手动安装 mt-dev-cli"
fi

# ─── Step 5: 配置 Supabase 连接 ───────────────────────────────────────────
# 知识库仓库自带 config/supabase.json（随 clone 就位）。此处只校验：有效配置直接用；
# 缺失则写入占位模板并提示；仍为占位符则提示手动填写（无独立可信源，不做自我拷贝）。
echo ""
echo "🔑 Step 5: 配置 Supabase 连接..."
SUPABASE_CFG="$KNOWLEDGE_REPO/config/supabase.json"
if [[ -f "$SUPABASE_CFG" ]] && ! grep -q '__SUPABASE_URL__\|__SUPABASE_ANON_KEY__' "$SUPABASE_CFG" 2>/dev/null; then
  echo "   ⏭️  supabase.json 已存在且为有效配置，跳过"
elif [[ -f "$SUPABASE_CFG" ]]; then
  echo "   ⚠️  supabase.json 仍为占位符，请手动填写真实配置: $SUPABASE_CFG"
else
  cat > "$SUPABASE_CFG" <<CFGEOF
{
  "url": "__SUPABASE_URL__",
  "anonKey": "__SUPABASE_ANON_KEY__",
  "business": "$BUSINESS"
}
CFGEOF
  echo "   ⚠️  未找到 config/supabase.json，已写入模板，请手动编辑: $SUPABASE_CFG"
fi

# ─── Step 6: 安装 state-cli ───────────────────────────────────────────────
echo ""
echo "🛠️  Step 6: 安装 state-cli..."
if [[ -f "$STATE_CLI_SRC" && -d "$STATE_PKG_SRC" ]]; then
  cp "$STATE_CLI_SRC" "$BIN_DIR/state-cli"
  chmod +x "$BIN_DIR/state-cli"
  STATE_PKG_DST="$WORKSPACE_ROOT/.scripts/state-cli/state_cli"
  mkdir -p "$STATE_PKG_DST"
  cp "$STATE_PKG_SRC"/*.py "$STATE_PKG_DST/"
  echo "   ✅ state-cli 已安装到 $BIN_DIR/state-cli"
else
  echo "   ⚠️  state-cli 源文件不存在: $STATE_CLI_SRC / $STATE_PKG_SRC"
fi

if command -v state-cli &>/dev/null; then
  echo "   ✅ state-cli 已在 PATH 中"
elif [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  echo "   ⚠️  请将 $BIN_DIR 添加到 PATH: export PATH=\"$BIN_DIR:\$PATH\""
fi

# ─── Step 7: 预装外部市场 skill（有则跳过，无则 mtskills --dir 拉取）──────────
# 安装命令口径以 atomic-tools.md「未安装时的处理方式」安装表为单一真源；此处仅做 bootstrap 预装，
# `AGENTS.md` 步骤零 0A 会在运行时按同一张表兜底懒装（缺失工具不阻塞本脚本初始化）。
echo ""
echo "🧩 Step 7: 预装外部市场 skill 到 $SKILLS_DIR..."
if command -v mtskills &>/dev/null; then
  for sk in "${REQUIRED_SKILLS[@]}"; do
    if [[ -d "$SKILLS_DIR/$sk" ]]; then
      echo "   ⏭️  $sk 已存在，跳过"
    else
      echo "   📥 安装 $sk -> $SKILLS_DIR ..."
      if mtskills i "$sk" --dir "$SKILLS_DIR" -y; then
        echo "   ✅ $sk 安装完成"
      else
        echo "   ⚠️  $sk 安装失败（不阻塞初始化，排查流程会在用到时按需重试）"
      fi
    fi
  done
else
  echo "   ⚠️  mtskills 不可用，跳过预装（排查流程会在用到时按需安装）"
fi

# ─── 完成 ─────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════"
echo "🎉 duty-agent ($BUSINESS) 初始化完成！"
echo ""
echo "目录结构:"
echo "  $WORKSPACE_ROOT/"
echo "  ├── trade-hotel-ai/        (知识库 & skill 仓库)"
echo "  │   ├── oncall/skills/"
echo "  │   ├── knowledge/"
echo "  │   └── config/supabase.json"
echo "  ├── <业务仓库>/            (业务源码，与知识库同级，直接克隆到此)"
echo "  ├── .bin/                  (state-cli 等可执行文件)"
echo "  └── .scripts/              (运行时脚本)"
echo ""
echo "外部市场 skill 目录: $SKILLS_DIR/  (logcenter-query-cli 等，mtskills --dir 安装)"
echo ""
echo "下一步:"
echo "  source $ENV_FILE"
echo "════════════════════════════════════════════"
